### PR TITLE
The uglifyjs module used is outdated, API has changed

### PR DESCRIPTION
**Pull request by dzhng**
Updated the handler to use the new minify() function in updated API.

### CODE REVIEW

**Comment by mojowen** [comment]
Thanks @dzz0615 for posting the fix

**Comment by joefru** [comment]
Nice work, @dzz0615. This helped me greatly.

**Comment by kwerty** [comment]
Please post this fix to the version on NPM, it would have saved me 30+ minutes of debugging.

**Comment by jacargentina** [comment]
@mape: dont u have time to merge this? Or there is some other module achieving the very same so connect-assertmanager-handlers is not mantained anymore?

**Pull request closed without merging**
